# Generated by Django 6.1 on 2026-08-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('elevation_gain', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Difficult', 'Difficult')], max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
